openapi: 3.0.0
info:
  version: "1.0.0-oas3"
  title: Notifications
  description: >-
    These are operations that can be used to send notification to users using a
    service bus queue
paths:
  /notifications:
    post:
      responses:
        '200':
          description: OK
      requestBody:
        $ref: '#/components/requestBodies/SendUserNotification'
components:
  requestBodies:
    SendUserNotification:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendUserNotificationMessage'
      description: The user to create.
      required: true
  schemas:
    SendUserNotificationMessage:
      type: object
      required:
        - id
        - template
        - to
        - subject
        - channel
      properties:
        id:
          type: string
          format: guid
          description: Unique identifier for the notification processing
          example: 413864a7-f8a1-4914-a952-0d2e9ae5b4b4
        template:
          type: string
          example: pp-usernotification-stepcompleted
          description: Code of the template to be used when sending the notification
        to:
          type: object
          properties:
            email:
              type: array
              items:
                type: string
                description: >-
                  email address of the account that will receive the
                  notification
                example: johndoe@iadb.org
            roles:
              type: array
              items:
                type: string
                description: >-
                  roles of the account that will receive the
                  notification
                example: vpc manager
        variables:
          type: array
          description: >-
            List of variables to replace in the notification template. These
            variables may be in either the subject or the body
          items:
            type: object
            properties:
              key:
                type: string
                description: >-
                  Unique identifier of the value to be replaced. For instance,
                  in the template a variable can be specified like 
                  [operation-number]. In this case you should provide
                  operation-numer only as key
                example: operation-number
              value:
                type: string
                description: Replace value for the variable
                example: UR-L1050
        channel:
          type: string
          description: Notification channel through which the notification is sent
          example: email
          enum:
            - email
            - application