openapi: 3.0.0
info:
  version: "1.0.0"
  title: OData 
  description: These APIs allow a client to interact with the calendar of countries
paths:
  '/v1/countryCalendar':
    get:
      parameters:
        - name: $select
          in: query
          description: Limits the properties returned in the result.
          required: true
          schema:
            type: string
        - name: $expand
          in: query
          description: Indicates the related entities to be represented inline. The maximum depth is 2.
          required: true
          schema:
            type: string
        - name: $filter
          in: query
          description: Restricts the set of items returned. The maximum number of expressions is 100. The allowed functions are allfunctions.
          required: true
          schema:
            type: string
        - name: $orderby
          in: query
          description: Specifies the order in which items are returned. The maximum number of expressions is 5.
          required: true
          schema:
            type: string
        - name: $top
          in: query
          description: Limits the number of items returned from a collection.
          required: true
          schema:
            type: integer
        - name: $skip
          in: query
          description: Excludes the specified number of items of the queried collection from the result.
          required: true
          schema:
            type: integer
        - name: $count
          in: query
          description: Indicates whether the total count of items within a collection are returned in the result.
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CountryCalendarSchema'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/fabs-co/idbschemas/master/global/baseapi.yaml#/error/base'
components:
  schemas:
    CountryCalendarSchema:
      type: object
      required:
        - countryCode
        - countryName
        - calendarDate
        - isHoliday
        - dayCode
      properties:
        countryCode:
          type: string
          description: ISO Code of the country
          example: US
        countryName:
          type: string
          description: Name of the country
          example: UNITED STATES
        calendarDate:
          type: string
          format: datetime
          description: Date
          example: '2020-07-04 00:00:00.000'
        isHoliday:
          type: boolean
          description: Holidays flag
        dayCode:
          type: string
          description: Type of the day
          example: Weekend

