openapi: 3.0.0
info:
  version: "1.0.0"
  title: Microsoft Graph Integration
  description: Allows to interaction against the Micrososft graph API to perform delegated actions with the application
paths:
  '/calendars/{calendar-id}':
    post:
      tags:
        - calendars
      summary: Create calendar invitation
      description: Create calendar invitation
      parameters: 
      - name: authorization
        in: header
        required: true
        description: session token provided by MS Graph
        schema:
          type: string
        
      - name: calendar-id
        in: path
        required: true
        description: Identify the calendar where the event will be created
        schema:
          type: string
          description: Id of office online calendar element
          example: AQMkADg4ATdmYzVhLTQxYzctNDUzNS04NjBlLTdjYjIyATFhZDI2ZQBGAAADNOG_5wQdxUao2Tg14XQBegcAsAY1ki5x0E6JhU_6vrKeAgAAAgEGAAAAsAY1ki5x0E6JhU_6vrKeAgAAAhW-AAAAa
      requestBody:
        $ref: '#/components/requestBodies/Event'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventSchema'
        '400':
          description: Bad request
        '401':
          description: Unathorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSchema'
  '/calendars/event/{event-id}':
    put:
      tags:
        - calendars
      summary: Update calendar invitation
      description: Update calendar invitation
      parameters: 
        - name: authorization
          in: header
          required: true
          description: session token provided by MS Graph
          schema:
            type: string
        - name: event-id
          in: path
          required: true
          description: Identify the event that will be updated
          schema:
            type: string
            description: Id of office online calendar event element
            example: AQMkADg4ATdmYzVhLTQxYzctNDUzNS04NjBlLTdjYjIyATFhZDI2ZQBGAAADNOG_5wQdxUao2Tg14XQBegcAsAY1ki5x0E6JhU_6vrKeAgAAAgEGAAAAsAY1ki5x0E6JhU_6vrKeAgAAAhW-AAAA
      requestBody:
        $ref: '#/components/requestBodies/EventUpdate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventSchema'
        '400':
          description: Bad request
        '401':
          description: Unathorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSchema'
    delete:
      tags:
        - calendars
      summary: Deletes calendar invitation
      description: Deletes calendar invitation
      parameters: 
      - name: authorization
        in: header
        required: true
        description: session token provided by MS Graph
        schema:
          type: string
        
      - name: event-id
        in: path
        required: true
        description: Identify the calendar event to be deleted
        schema:
          type: string
          description: Id of office online calendar event element
          example: AAMkADg4ATdmYzVhLTQxYzctNDUzNS04NjBlLTdjYjIyATFhZDI2ZQBGAAADNOG_5wQdxUao2Tg14XQBegcAsAY1ki5x0E6JhU_6vrKeAgAAAgEGAAAAsAY1ki5x0E6JhU_6vrKeAgAAAhW-AAAA
      responses:
          '200':
            description: OK
          '400':
            description: Bad request
          '401':
            description: Unathorized
          '403':
            description: Forbidden
          '404':
            description: Not found
          '500':
            description: Internal server error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorSchema'
components:
  requestBodies:
    Event:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EventSchema'
      description: The user to create.
      required: true
    EventUpdate:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EventUpdateSchema'
      description: The user to create.
      required: true
  schemas:
    EventSchema:
      type: object
      properties:
        attendees: 
          type: array
          items: 
            $ref: "#/components/schemas/AttendeeSchema"
        body:
          $ref: "#/components/schemas/BodySchema"
        bodyPreview: 
            type: string
        categories: 
            type: string
        changeKey: 
            type: string
        createdDateTime:
            type: string
        end:
          $ref: "#/components/schemas/DateTimeTimeZoneSchema"
        hasAttachments: 
            type: boolean
        iCalUId: 
            type: string
        id:
            type: string
        importance: 
          type: string
        isAllDay:
          type: boolean
        isCancelled: 
          type: boolean
        isOnlineMeeting: 
          type: boolean
        isOrganizer: 
          type: boolean
        isReminderOn: 
          type: boolean
        lastModifiedDateTime: 
          type: string
        location: 
           $ref: "#/components/schemas/LocationSchema"
        locations: 
            type: array
            items: 
              $ref: "#/components/schemas/LocationSchema"
        onlineMeeting: 
            $ref: "#/components/schemas/OnlineMeetingInfoSchema"
        onlineMeetingProvider: 
          type: string
        onlineMeetingUrl: 
          type: string
        organizer: 
            $ref: "#/components/schemas/RecipientSchema"
        originalEndTimeZone: 
          type: string
        originalStart:
          type: string
        originalStartTimeZone: 
          type: string
        recurrence:
             $ref: "#/components/schemas/PatternedRecurrenceSchema"
        reminderMinutesBeforeStart: 
            type: integer
        responseRequested: 
          type: boolean
        responseStatus:
          $ref: "#/components/schemas/ResponseStatusSchema"
        sensitivity: 
          type: string
        seriesMasterId: 
          type: string
        showAs: 
          type: string
        start:
            $ref: "#/components/schemas/DateTimeTimeZoneSchema"
        subject: 
          type: string
        type: 
          type: string
        webLink: 
          type: string
        attachments:
            type: array
            items: 
              $ref: "#/components/schemas/AttachmentSchema"
        calendar: 
              $ref: "#/components/schemas/CalendarSchema"
        extensions: 
            type: array
            items: 
              $ref: "#/components/schemas/ExtensionSchema"
        instances: 
            type: array
            items: 
              $ref: "#/components/schemas/EventSchema"
      required: 
        - start
        - attendees
        - body
        - end
        - subject
      externalDocs:
        description: event resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0
    EventUpdateSchema:
      type: object
      properties:
        attendees: 
          type: array
          items: 
            $ref: "#/components/schemas/AttendeeSchema"
        body:
          $ref: "#/components/schemas/BodySchema"
        bodyPreview: 
            type: string
        end:
          $ref: "#/components/schemas/DateTimeTimeZoneSchema"
        importance: 
          type: string
        isAllDay:
          type: boolean
        isOnlineMeeting: 
          type: boolean
        isReminderOn: 
          type: boolean
        location: 
           $ref: "#/components/schemas/LocationSchema"
        locations: 
            type: array
            items: 
              $ref: "#/components/schemas/LocationSchema"
        onlineMeetingProvider: 
          type: string
        recurrence:
             $ref: "#/components/schemas/PatternedRecurrenceSchema"
        reminderMinutesBeforeStart: 
            type: integer
        responseRequested: 
          type: boolean
        sensitivity: 
          type: string
        showAs: 
          type: string
        start:
            $ref: "#/components/schemas/DateTimeTimeZoneSchema"
        subject: 
          type: string
      externalDocs:
        description: event resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0    
    CalendarSchema:
      type: object
      required:
        - name
        - id
      properties:
        id:
          type: string
          description: Id of office online calendar element
          example: AQMkADg4ATdmYzVhLTQxYzctNDUzNS04NjBlLTdjYjIyATFhZDI2ZQBGAAADNOG_5wQdxUao2Tg14XQBegcAsAY1ki5x0E6JhU_6vrKeAgAAAgEGAAAAsAY1ki5x0E6JhU_6vrKeAgAAAhW-AAAA
        name:
          type: string
          description: User friendly name showed to users in the office interface
          example: VPC/VPC
        allowedOnlineMeetingProviders:
          type: array
          items:
            type: string
        canEdit: 
          type: boolean
        canShare: 
          type: boolean
        canViewPrivateItems: 
          type: boolean
        changeKey: 
          type: string
        color: 
          type: string
        defaultOnlineMeetingProvider: 
          type: string
        isDefaultCalendar: 
          type: boolean
        isRemovable: 
          type: boolean
        isTallyingResponses: 
          type: boolean
        owner:
          $ref : '#/components/schemas/EmailAddressSchema'
      externalDocs:
        description: calendar resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0
    AttendeeSchema:
      type: object
      properties:
        status: 
          $ref: '#/components/schemas/ResponseStatusSchema'
        type:
            type: string
        emailAddress:
          $ref : '#/components/schemas/EmailAddressSchema'
      externalDocs:
        description: attendee resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/attendee?view=graph-rest-1.0
    EmailAddressSchema:
      type: object
      properties:
        address:
          type: string
        name:
          type: string
      externalDocs:
        description: emailAddress resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/emailaddress?view=graph-rest-1.0
    BodySchema:
      type: object
      properties:
        content: 
          type: string
        contentType:
          type: string
      externalDocs:
        description: itemBody resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/itembody?view=graph-rest-1.0
    LocationSchema:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/PhysicalAddressSchema'
        coordinates:
          $ref: '#/components/schemas/OutlookGeoCoordinatesSchema'
        displayName: 
          type: string
        locationEmailAddress: 
          type: string
        locationUri: 
          type: string
        locationType: 
          type: string
        uniqueId: 
          type: string
        uniqueIdType: 
          type: string
      externalDocs:
        description: Location resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/location?view=graph-rest-1.0
    OnlineMeetingInfoSchema:
      type: object
      properties:
        conferenceId: 
          type: string
        joinUrl: 
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/PhoneSchema'
        quickDial: 
          type: string
        tollFreeNumbers:
          type: string
        tollNumber: 
          type: string
      externalDocs:
        description: Location resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/location?view=graph-rest-1.0
    RecipientSchema:
      type: object
      properties:
        emailAddress:
          $ref: '#/components/schemas/EmailAddressSchema'
      externalDocs:
        description: recipient resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/recipient?view=graph-rest-1.0
    PatternedRecurrenceSchema:
      type: object
      properties:
        Pattern:
          $ref: '#/components/schemas/RecurrencePatternSchema'
        Range:
          $ref: '#/components/schemas/RecurrenceRangeSchema'
      externalDocs:
        description: patternedRecurrence resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-1.0
    RecurrenceRangeSchema:
      type: object
      properties:
        endDate: 
          type: string
        numberOfOccurrences: 
          type: integer
        recurrenceTimeZone: 
          type: string
        startDate: 
          type: string
        type: 
          type: string
      externalDocs:
        description: recurrenceRange resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/recurrencerange?view=graph-rest-1.0
    RecurrencePatternSchema:
      type: object
      properties:
        dayOfMonth:
          type: integer
        daysOfWeek:
          type: array
          items:
            type: string
        firstDayOfWeek: 
          type: string
        index: 
          type: string
        interval: 
          type: integer
        month:
          type: integer
        type:
          type: string
      externalDocs:
        description: recurrencePattern resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/recurrencepattern?view=graph-rest-1.0
    OutlookGeoCoordinatesSchema:
      type: object
      properties:
        accuracy: 
          type: integer
        altitude: 
          type: integer
        altitudeAccuracy: 
          type: integer
        latitude: 
          type: integer
        longitude: 
          type: integer
      externalDocs:
        description: outlookGeoCoordinates resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/outlookgeocoordinates?view=graph-rest-1.0
    PhoneSchema:
      type: object
      properties:
        number:
          type: string
        type:
          type: string
      externalDocs:
        description: phone resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/phone?view=graph-rest-1.0
    PhysicalAddressSchema:
      type: object
      properties:
        city: 
          type: string
        countryOrRegion:
          type: string
        postalCode: 
          type: string
        state: 
          type: string
        street: 
          type: string
      externalDocs:
        description: physicalAddress resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/physicaladdress?view=graph-rest-1.0
    ResponseStatusSchema:
      type: object
      properties:
        response:
          type: string
        time:
          type: string
      externalDocs:
        description: responseStatus resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/ResponseStatus?view=graph-rest-1.0
    DateTimeTimeZoneSchema:
      type: object
      properties:
        dateTime:
          type: string
        timeZone:
          type: string
      externalDocs:
        description: dateTimeTimeZone resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/DateTimeTimeZone?view=graph-rest-1.0
    AttachmentSchema:
      type: object
      properties:
        contentType:
          type: string
        id:
          type: string
        isInline:
          type: boolean
        lastModifiedDateTime:
          type: string
        name: 
          type: string
        size:
          type: integer
        contentBytes:
          type: string
      externalDocs:
        description: attachment resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/attachment?view=graph-rest-1.0
    ExtensionSchema:
      type: object
      properties:
        id:
          type: string
      externalDocs:
        description: extension resource type
        url: https://docs.microsoft.com/en-us/graph/api/resources/Extension?view=graph-rest-1.0
    ErrorSchema:
      type: object
      properties:
        title:
          type: string
          example: the provided parameter is invalid
          description: >-
            A short, human-readable title for the general error type; the title
            should not change for given types
        detail:
          type: string
          example: The parameter stepId did not return a valid entity
          description: A human-readable description of the specific error
        status:
          type: integer
          example: 500
          description: >-
            Conveying the HTTP status code; this is so that all information is
            in one place, but also to correct for changes in the status code due
            to the usage of proxy servers. The status member, if present, is
            only advisory as generators MUST use the same status code in the
            actual HTTP response to assure that generic HTTP software that does
            not understand this format still behaves correctly
        developerMessage:
          type: string
          example: The entity for the provided id was not found in the database
          description: >-
            A message that can be used by a developer for solving the specific
            issue
          
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Kavoku/MSGraph/1.0.0
